# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "goteborg"
license = "MIT"
licenselink = "https://github.com/joakimskoog/hugo-theme-goteborg/blob/master/LICENSE"
description = "Clean theme for my personal site"
tags = ["blog", "clean", "minimal"]
features = ["blog"]
min_version = "0.41"

[author]
  name = "Joakim Skoog"
  homepage = "https://joakimskoog.com"

# If porting an existing theme
[original]
  name = "goteborg"
  homepage = "https://github.com/joakimskoog/hugo-theme-goteborg"
  repo = "https://github.com/joakimskoog/hugo-theme-goteborg"